package main

// lockfile.go — aril.lock, the committed record of the exact resolved
// dependency set (RFC-0008 §The lockfile). `aril get` writes it; a build reads
// it (later work) to resolve offline against the cache. The format is the same
// closed-schema line shapes the manifest reader accepts, so no third-party TOML
// library enters the compiler core (D19).

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// lockEntry pins one resolved module: its declared source + version, the exact
// commit the version resolved to at fetch time, and a content hash of the
// fetched tree (reproducibility + tamper check, RFC-0008 §fetch).
type lockEntry struct {
	name     string
	source   string
	version  string
	resolved string // the commit the version named at fetch time
	hash     string // sha256 over the fetched module tree
}

const lockFileName = "aril.lock"

// writeLock renders the lockfile deterministically (entries sorted by name) so
// re-running `aril get` produces a stable, reviewable diff.
func writeLock(dir string, entries []lockEntry) error {
	sorted := append([]lockEntry(nil), entries...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].name < sorted[j].name })
	var b strings.Builder
	b.WriteString("# aril.lock — generated by `aril get`; do not edit by hand.\n")
	b.WriteString("# Pins every dependency (direct + transitive) to an exact commit + content hash.\n")
	// Values are quoted verbatim (not %q-escaped) to match the reader's
	// literal `tomlString` (which strips the outer quotes without unescaping) —
	// so a `source` with backslashes (a Windows local path) roundtrips. The
	// values are machine-derived (manifest strings, hex commit/hash) and never
	// contain a quote or newline.
	for _, e := range sorted {
		fmt.Fprintf(&b, "\n[[module]]\nname = \"%s\"\nsource = \"%s\"\nversion = \"%s\"\nresolved = \"%s\"\nhash = \"%s\"\n",
			e.name, e.source, e.version, e.resolved, e.hash)
	}
	return os.WriteFile(filepath.Join(dir, lockFileName), []byte(b.String()), 0o644)
}

// readLock parses aril.lock. A missing file yields (nil, nil) — a project with
// no fetched dependencies has no lock.
func readLock(dir string) ([]lockEntry, error) {
	path := filepath.Join(dir, lockFileName)
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("aril: read %s: %w", lockFileName, err)
	}
	var entries []lockEntry
	var cur *lockEntry
	for i, raw := range strings.Split(string(data), "\n") {
		line := strings.TrimSpace(stripComment(raw))
		if line == "" {
			continue
		}
		if line == "[[module]]" {
			entries = append(entries, lockEntry{})
			cur = &entries[len(entries)-1]
			continue
		}
		key, val, ok := strings.Cut(line, "=")
		if !ok {
			return nil, fmt.Errorf("aril: %s:%d: expected `key = value`", lockFileName, i+1)
		}
		if cur == nil {
			return nil, fmt.Errorf("aril: %s:%d: key outside any [[module]]", lockFileName, i+1)
		}
		s, err := tomlString(strings.TrimSpace(val))
		if err != nil {
			return nil, fmt.Errorf("aril: %s:%d: %v", lockFileName, i+1, err)
		}
		switch strings.TrimSpace(key) {
		case "name":
			cur.name = s
		case "source":
			cur.source = s
		case "version":
			cur.version = s
		case "resolved":
			cur.resolved = s
		case "hash":
			cur.hash = s
		default:
			return nil, fmt.Errorf("aril: %s:%d: unknown key %q", lockFileName, i+1, key)
		}
	}
	return entries, nil
}
